routes/web.php
<?php


// ====================================================================================================================
// utility ============================================================================================================
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

// ====================================================================================================================
// Controller =========================================================================================================
use App\Http\Controllers\SocialiteController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LabController;
use App\Http\Controllers\LoaderController;
use App\Http\Controllers\SitemapController;

// ====================================================================================================================
// Frontend ===========================================================================================================
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\KontakController;
use App\Http\Controllers\Frontend\GaleriController;
use App\Http\Controllers\Frontend\PendaftaranController;
use App\Http\Controllers\Admin\Pendaftaran\GFormController;

// ====================================================================================================================
// Tentang Kami =======================================================================================================
use App\Http\Controllers\Frontend\About\Kepengurusan\StrukturController;
use App\Http\Controllers\Frontend\About\Kepengurusan\BidangController;
use App\Http\Controllers\Frontend\About\Kepengurusan\PeriodeController;
use App\Http\Controllers\Frontend\About\SejarahController;
use App\Http\Controllers\Frontend\AnggotaController;
use App\Http\Controllers\Frontend\ArtikelController;
use App\Http\Controllers\Frontend\Pendaftaran\SensusController;
use App\Http\Controllers\Frontend\AboutController;
use Illuminate\Http\Request;

// ====================================================================================================================
// ====================================================================================================================



// auth ===============================================================================================================
Route::controller(LoginController::class)->group(function () {
    Route::get('/login', 'index')->name("login");
    Route::post('/login', 'check_login')->name("login.check_login");
    Route::get('/logout', 'logout')->name("login.logout");
});

Route::controller(SocialiteController::class)->group(function () {
    Route::get('/auth/{provider}', 'redirectToProvider');
    Route::get('/auth/{provider}/callback', 'handleProvideCallback');
});
// ====================================================================================================================

// home default =======================================================================================================
Route::controller(HomeController::class)->group(function () {
    Route::get('/', 'index')->name("home");
    Route::get('/periode/{periode:slug}', 'periode')->name("periode");
});

Route::get('/admin', fn () => Redirect::route('dashboard'));
// ====================================================================================================================

// artikel ============================================================================================================
$prefix = 'artikel';
Route::controller(ArtikelController::class)->prefix($prefix)->group(function () use ($prefix) {
    Route::get('/', 'index')->name($prefix);
    Route::get('/{model:slug}', 'detail')->name("$prefix.detail");
});
// ====================================================================================================================

// Periode Kepengurusan ===============================================================================================
$name = 'tentang';
Route::group(['prefix' => $name], function () use ($name) {
    $prefix = 'kepengurusan';
    Route::group(['prefix' => $prefix], function () use ($name, $prefix) {
        $name = "$name.$prefix"; // tentang.kepengurusan

        // struktur
        $prefix = 'struktur';
        Route::controller(StrukturController::class)->prefix($prefix)->group(function () use ($name, $prefix) {
            $name = "$name.$prefix"; // tentang.kepengurusan.struktur
            Route::get('/', 'index')->name($name);
            Route::get('/{periode:slug}', 'periode')->name("$name.periode");
        });

        // periode
        $prefix = 'periode';
        Route::controller(PeriodeController::class)->prefix($prefix)->group(function () use ($name, $prefix) {
            $name = "$name.$prefix"; // tentang.kepengurusan.periode
            Route::get('/', 'index')->name($name);
        });

        // bidang
        Route::get('/bidang/{jabatan:slug}', [BidangController::class, 'index'])->name("$name.bidang");
    });

    // sejarah
    Route::get('/sejarah', [SejarahController::class, 'index'])->name("$name.sejarah");
});
// ====================================================================================================================

// Anggota ============================================================================================================
$name = 'anggota';
Route::controller(AnggotaController::class)->prefix($name)->group(function () use ($name) {
    Route::get('/', 'index')->name($name);
    Route::get('/{anggota:id}', 'anggota')->name("$name.id");
});
// ====================================================================================================================

// Kontak =============================================================================================================
$name = 'kontak';
Route::controller(KontakController::class)->prefix($name)->group(function () use ($name) {
    Route::get('/', 'index')->name($name);
    Route::post('/send', 'insert')->name("$name.send");
    Route::get('/faq', 'faq')->name("$name.faq");
});
// ====================================================================================================================

// Galeri =============================================================================================================
$name = 'galeri';
Route::controller(GaleriController::class)->prefix($name)->group(function () use ($name) {
    Route::get('/', 'index')->name($name);
    Route::get('/detail/{model:slug}', 'detail')->name("$name.detail");
});
// ====================================================================================================================

// Pendaftaran ========================================================================================================
$name = 'pendaftaran';
Route::prefix($name)->group(function () use ($name) {
    Route::controller(PendaftaranController::class)->group(function () use ($name) {
        Route::get('/', 'index')->name($name);
    });

    $prefix = 'sensus';
    Route::controller(SensusController::class)->prefix($prefix)->group(function () use ($name, $prefix) {
        $name = "$name.$prefix";
        Route::get('/', 'index')->name($name);
        Route::post('/insert', 'insert')->name("$name.insert");
    });
});
// ====================================================================================================================

// dashboard ==========================================================================================================
Route::get('/dashboard', function () {
    if (!auth()->user()) return Redirect::route('login');
    if (auth_has_role(config('app.super_admin_role'))) {
        return Redirect::route('admin.dashboard');
    } else {
        return Redirect::route('member.dashboard');
    }
})->name("dashboard");
// ====================================================================================================================

// katalog ============================================================================================================
$prefix = 'katalog';
Route::controller(KatalogController::class)->prefix($prefix)->group(function () use ($prefix) {
    Route::get('/', 'index')->name($prefix);
    Route::get('/{model:slug}', 'detail')->name("$prefix.detail");
});
// ====================================================================================================================

// AboutUs ============================================================================================================
$name = 'about';
Route::controller(AboutController::class)->prefix($name)->group(function () use ($name) {
    Route::get('/', 'index')->name($name);
});
// ====================================================================================================================

// Marketplace ========================================================================================================
$name = 'marketplace';
Route::controller(MarketplaceController::class)->prefix($name)->group(function () use ($name) {
    Route::get('/', 'index')->name($name);
});
// ====================================================================================================================







// Utility ============================================================================================================
$prefix = 'loader';
Route::controller(LoaderController::class)->prefix($prefix)->group(function () {
    Route::prefix('js')->group(function () {
        Route::any('{path}', 'js')->where('path', '.*');
    });
    Route::prefix('css')->group(function () {
        Route::any('{path}', 'css')->where('path', '.*');
    });
});
// ====================================================================================================================

app/Models/Keanggotaan/Kontak.php
<?php

namespace App\Models\Keanggotaan;

use Haruncpi\LaravelUserActivity\Traits\Loggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kontak extends Model
{
    use HasFactory, Loggable;

    protected $fillable = [
        'jenis_id',
        'anggota_id',
        'nilai',
    ];

    protected $primaryKey = 'id';
    protected $table = 'anggota_kontaks';
    const tableName = 'anggota_kontaks';

    public function anggota()
    {
        return $this->belongsTo(Anggota::class, 'anggota_id', 'id');
    }

    public function jenis()
    {
        return $this->belongsTo(KontakJenis::class, 'jenis_id', 'id');
    }
}

app/Models/Menu/Frontend.php
<?php

namespace App\Models\Menu;

use Haruncpi\LaravelUserActivity\Traits\Loggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

class Frontend extends Model
{
    use HasFactory, Loggable;

    protected $fillable = [
        'parent_id',
        'title',
        'icon',
        'route',
        'sequence',
        'active',
        'type',
    ];
    protected $primaryKey = 'id';
    protected $table = 'p_menu_frontends';
    const tableName = 'p_menu_frontends';
    const feCacheKey = 'feMenuFrontend';

    public static function getAll()
    {
        $table = static::tableName;
        DB::statement("SET SQL_MODE=''");
        $menu = DB::table($table)->select([
            "$table.id",
            "$table.parent_id",
            "$table.title",
            "$table.icon",
            "$table.route",
            "$table.sequence",
            DB::raw("b.title as parent"),
            DB::raw("$table.active as status"),
            "$table.type",
        ]);
        $menu->leftJoin("$table as b", "b.id", "=", "$table.parent_id");
        $menu->groupBy("$table.id");
        $menu->orderBy("$table.sequence", 'asc');
        return $menu->get();
    }

    public static function getFeViewData()
    {
        return Cache::rememberForever(static::feCacheKey, function () {
            $table = static::tableName;
            DB::statement("SET SQL_MODE=''");
            $menu = DB::table($table)->select([
                "$table.id",
                "$table.parent_id",
                "$table.title",
                "$table.icon",
                "$table.route",
                "$table.sequence",
                DB::raw("b.title as parent"),
                DB::raw("$table.active as status"),
                "$table.type",
            ])
                ->leftJoin("$table as b", "b.id", "=", "$table.parent_id")
                ->groupBy("$table.id")
                ->where("$table.active", '=', 1)
                ->orderBy("$table.sequence", 'asc');

            return $menu->get();
        });
    }

    public static function feClearCache()
    {
        return Cache::pull(static::feCacheKey);
    }

    public static function all_view()
    {
        $table = self::tableName;
        DB::statement("SET SQL_MODE=''");
        $menu = DB::table($table)->select([
            "$table.id",
            "$table.parent_id",
            "$table.title",
            "$table.icon",
            "$table.route",
            "$table.sequence",
            DB::raw("b.title as parent"),
            DB::raw("$table.active as status"),
            "$table.type",
        ])
            ->leftJoin("$table as b", "b.id", "=", "$table.parent_id")
            ->groupBy("$table.id")
            ->where("$table.active", '=', 1)
            ->orderBy("$table.sequence", 'asc');

        return $menu->get();
    }
}

app/Http/Controllers/Frontend/KontakController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Contact\FAQ;
use App\Models\Contact\ListContact;
use App\Models\Contact\Message as ContactMessage;
use Illuminate\Http\Request;
use League\Config\Exception\ValidationException;

class KontakController extends Controller
{
    private $validate_model = [
        'nama' => ['required', 'string', 'max:255'],
        'email' => ['required', 'string', 'max:255', 'email'],
        'message' => ['required', 'string'],
    ];

    public function index(Request $request)
    {
        $page_attr = [
            'title' => 'Kontak',
        ];

        $contacts = ListContact::where('status', '=', 1)->get();
        $faqs = FAQ::where('status', '=', 1)->get();

        $data = compact('page_attr', 'contacts', 'faqs');
        $data['compact'] = $data;
        return view('pages.frontend.kontak', $data);
    }

    public function faq(Request $request)
    {
        $page_attr = [
            'title' => 'FAQ',
        ];

        $faqs = FAQ::where('status', '=', 1)->get();
        $data = compact('page_attr', 'faqs');
        $data['compact'] = $data;
        return view('pages.frontend.faq', $data);
    }

    public function insert(Request $request): mixed
    {
        try {
            $request->validate($this->validate_model);

            $model = new ContactMessage();
            $model->nama = $request->nama;
            $model->email = $request->email;
            $model->message = $request->message;
            $model->save();
            return response()->json();
        } catch (ValidationException $error) {
            return response()->json([
                'message' => 'Something went wrong',
                'error' => $error,
            ], 500);
        }
    }
}

resources/views/pages/admin/kontak/faq.blade.php
@extends('layouts.admin.master')

@section('content')
    @php
        $can_insert = auth_can(h_prefix('insert'));
        $can_update = auth_can(h_prefix('update'));
        $can_delete = auth_can(h_prefix('delete'));
        $can_setting = auth_can(h_prefix('setting'));
    @endphp
    <div class="card mt-3">
        <div class="card-body">
            <div class="card-title d-md-flex flex-row justify-content-between">
                <div>
                    <h6 class="mt-2 text-uppercase">Data {{ $page_attr['title'] }}</h6>
                </div>
                @if ($can_insert)
                    <div>
                        <button type="button" class="btn btn-rounded btn-primary btn-sm" data-bs-effect="effect-scale"
                            data-bs-toggle="modal" href="#modal-default" onclick="addFunc()" data-target="#modal-default">
                            <i class="fas fa-plus"></i> Tambah
                        </button>
                    </div>
                @endif
            </div>

            <hr class="mt-1 mb-0" />
            <div class="accordion accordion-flush" id="accordionOption">
                <div class="accordion-item">
                    <h6 class="accordion-header" id="headingSix">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#filterData" aria-expanded="false" aria-controls="filterData">
                            Filter Data
                        </button>
                    </h6>
                    <div id="filterData" class="accordion-collapse collapse" aria-labelledby="headingSix"
                        data-bs-parent="#accordionOption">
                        <div class="accordion-body">
                            <form action="javascript:void(0)" class="ml-md-3 mb-md-3" id="FilterForm">
                                <div class="form-group float-start me-2">
                                    <label for="filter_status">Status</label>
                                    <select class="form-control" id="filter_status" name="filter_status"
                                        style="max-width: 200px">
                                        <option value="">Semua</option>
                                        <option value="1">Digunakan</option>
                                        <option value="0">Tidak Digunakan</option>
                                    </select>
                                </div>

                                <div class="form-group float-start me-2">
                                    <label for="filter_type">Tipe</label>
                                    <select class="form-control" id="filter_type" name="filter_type"
                                        style="max-width: 200px">
                                        <option value="">Semua</option>
                                        <option value="1">Teks</option>
                                        <option value="2">Link</option>
                                    </select>
                                </div>
                            </form>
                            <div style="clear: both"></div>
                            <button type="submit" form="FilterForm" class="btn btn-rounded btn-sm btn-secondary mt-2"
                                data-toggle="tooltip" title="Refresh Filter Table">
                                <i class="fas fa-sync-alt me-1"></i> Terapkan filter
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            @if ($can_setting)
                <hr class="mt-1 mb-0" />
                <div class="accordion accordion-flush" id="setting_list_container">
                    <div class="accordion-item">
                        <h6 class="accordion-header" id="setting_list">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#settingList" aria-expanded="false" aria-controls="settingList">
                                Pengaturan
                            </button>
                        </h6>
                        <div id="settingList" class="accordion-collapse collapse" aria-labelledby="setting_list"
                            data-bs-parent="#setting_list_container">
                            <div class="accordion-body">
                                <form action="javascript:void(0)" class="ml-md-3 mb-md-3" id="setting_form">
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" name="visible" type="checkbox" id="settingTampilkan"
                                            {{ $setting->visible ? 'checked' : '' }}>
                                        <label class="form-check-label" for="settingTampilkan">Tampilkan</label>
                                    </div>

                                    <div class="form-group">
                                        <label class="form-label mb-1" for="title">Judul<span
                                                class="text-danger">*</span></label>
                                        <input type="text" id="title" name="title" class="form-control"
                                            placeholder="Judul" value="{{ $setting->title }}" required />
                                    </div>

                                    <div class="form-group">
                                        <label class="form-label mb-1" for="sub_title">Sub Judul<span
                                                class="text-danger">*</span></label>
                                        <input type="text" id="sub_title" name="sub_title" class="form-control"
                                            placeholder="Sub Judul" value="{{ $setting->sub_title }}" required />
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label mb-1" for="description">Keterangan</label>
                                        <textarea type="text" id="description" name="description" class="form-control" placeholder="Keterangan">{{ $setting->description }}</textarea>
                                    </div>
                                </form>
                                <div style="clear: both"></div>
                                <button type="submit" form="setting_form"
                                    class="btn btn-rounded btn-sm btn-secondary mt-2" data-toggle="tooltip"
                                    title="Simpan perubahan">
                                    <li class="fas fa-save mr-1"></li> Simpan Perubahan
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            @endif

            <table class="table table-striped table-hover w-100" id="tbl_main">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>Tipe</th>
                        <th>Status</th>
                        <th>Detail</th>
                        {!! $can_delete || $can_update ? '<th>Aksi</th>' : '' !!}
                    </tr>
                </thead>
                <tbody> </tbody>
            </table>
        </div>
    </div>

    <!-- End Row -->
    <div class="modal fade" id="modal-default">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content modal-content-demo">
                <div class="modal-header">
                    <h6 class="modal-title" id="modal-default-title"></h6><button aria-label="Tutup" class="btn-close"
                        data-bs-dismiss="modal"><span aria-hidden="true"></span></button>
                </div>
                <div class="modal-body">
                    <form action="javascript:void(0)" id="MainForm" name="MainForm" method="POST"
                        enctype="multipart/form-data">
                        <input type="hidden" name="id" id="id">
                        <div class="form-group">
                            <label class="form-label mb-1" for="nama">Nama <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="nama" name="nama"
                                placeholder="Enter Nama" required="" />
                        </div>
                        <div class="form-group">
                            <label class="form-label mb-1" for="link">Link <span class="text-danger">*</span></label>
                            <input type="url" class="form-control" id="link" name="link"
                                placeholder="Enter Link" required="" />
                        </div>
                        <div class="form-group">
                            <label class="form-label mb-1" for="jawaban">Jawaban <span
                                    class="text-danger">*</span></label>
                            <textarea type="text" class="form-control" rows="3" id="jawaban" name="jawaban"
                                placeholder="Enter Jawaban"> </textarea>
                        </div>
                        <div class="form-group">
                            <label class="form-label mb-1" for="type">Tipe</label>
                            <select class="form-control" style="width: 100%;" required="" id="type"
                                name="type">
                                <option value="1">Teks</option>
                                <option value="2">Link</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="form-label mb-1" for="status">Status</label>
                            <select class="form-control" style="width: 100%;" required="" id="status"
                                name="status">
                                <option value="1">Digunakan</option>
                                <option value="0">Tidak Digunakan</option>
                            </select>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" id="btn-save" form="MainForm">
                        <li class="fas fa-save mr-1"></li> Simpan Perubahan
                    </button>
                    <button class="btn btn-light" data-bs-dismiss="modal">
                        <i class="fas fa-times"></i>
                        Tutup
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-detail">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content modal-content-demo">
                <div class="modal-header">
                    <h6 class="modal-title" id="modal-detail-title">Detail</h6><button aria-label="Tutup"
                        class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true"></span></button>
                </div>
                <div class="modal-body" id="modal-detail-body">

                </div>
                <div class="modal-footer">
                    <button class="btn btn-light" data-bs-dismiss="modal">
                        <i class="fas fa-times"></i>
                        Tutup
                    </button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('stylesheet')
    <link rel="stylesheet" href="{{ asset_admin('plugins/datatable/css/dataTables.bootstrap5.min.css') }}" />
@endsection

@section('javascript')
    <script src="{{ asset_admin('plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset_admin('plugins/datatable/js/dataTables.bootstrap5.min.js') }}"></script>
    <script src="{{ asset_admin('plugins/loading/loadingoverlay.min.js', name: 'sash') }}"></script>
    <script src="{{ asset_admin('plugins/sweet-alert/sweetalert2.all.js', name: 'sash') }}"></script>
    <script src="{{ asset_admin('plugins/loading/loadingoverlay.min.js', name: 'sash') }}"></script>
    @php
        $resource = resource_loader(
            blade_path: $view,
            params: [
                'can_update' => $can_update ? 'true' : 'false',
                'can_delete' => $can_delete ? 'true' : 'false',
                'can_setting' => $can_setting ? 'true' : 'false',
                'page_title' => $page_attr['title'],
            ],
        );
    @endphp
    <script src="{{ $resource }}"></script>
@endsection